### PR TITLE
Assorted Maven build adjustments

### PR DESCRIPTION
**Pull request by gsmet**
@vsevel things looked quite good after your adjustments so I just made some minor adjustments to make things more in line with the latest Quarkiverse projects.

### CODE REVIEW

**Comment by vsevel** [comment]
thanks so much for taking a look.
I have my doubts on putting back the `it` profile.
I know that is what we should be doing.
but having it, would not skip those tests modules as expected. and that's was causing the issue. for instance this [build](https://github.com/quarkiverse/quarkus-freemarker/runs/1927354884?check_suite_focus=true):
```
2021-02-18T13:46:18.1455835Z [INFO] [INFO] -------------------------------------------------------
2021-02-18T13:46:18.1459962Z [INFO] [INFO]  T E S T S
2021-02-18T13:46:18.1467121Z [INFO] [INFO] -------------------------------------------------------
2021-02-18T13:46:19.1670987Z [INFO] [INFO] Running io.quarkiverse.it.freemarker.ConfigDefaultsTest
2021-02-18T13:46:21.1614519Z [INFO] Downloading from central: https://repo.maven.apache.org/maven2/io/quarkiverse/freemarker/quarkiverse-freemarker-integration-tests/0.2.0.CR1/quarkiverse-freemarker-integration-tests-0.2.0.CR1.pom
2021-02-18T13:46:21.5944377Z [INFO] [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 2.405 s <<< FAILURE! - in io.quarkiverse.it.freemarker.ConfigDefaultsTest
```

the reactor for the `perform:release` shows all test modules:
```
2021-02-18T13:46:21.9575981Z [INFO] [INFO] ------------------------------------------------------------------------
2021-02-18T13:46:21.9578434Z [INFO] [INFO] Reactor Summary for Quarkus - Freemarker - Parent 0.2.0.CR1:
2021-02-18T13:46:21.9580595Z [INFO] [INFO] 
2021-02-18T13:46:21.9582449Z [INFO] [INFO] Quarkus - Freemarker - Parent ...................... SUCCESS [01:34 min]
2021-02-18T13:46:21.9584873Z [INFO] [INFO] Quarkus - Freemarker - Runtime ..................... SUCCESS [ 31.284 s]
2021-02-18T13:46:21.9587069Z [INFO] [INFO] Quarkus - Freemarker - Deployment .................. SUCCESS [  7.820 s]
2021-02-18T13:46:21.9589319Z [INFO] [INFO] Quarkus - Freemarker - Integration tests ........... SUCCESS [  0.031 s]
2021-02-18T13:46:21.9591772Z [INFO] [INFO] Quarkus - Freemarker - Integration test - Configuration defaults FAILURE [  9.839 s]
2021-02-18T13:46:21.9594262Z [INFO] [INFO] Quarkus - Freemarker - Integration test - Legacy configuration SKIPPED
2021-02-18T13:46:21.9597070Z [INFO] [INFO] Quarkus - Freemarker - Integration test - Template sets SKIPPED
2021-02-18T13:46:21.9599348Z [INFO] [INFO] ------------------------------------------------------------------------
2021-02-18T13:46:21.9601259Z [INFO] [INFO] BUILD FAILURE
2021-02-18T13:46:21.9603074Z [INFO] [INFO] ------------------------------------------------------------------------
2021-02-18T13:46:21.9604980Z [INFO] [INFO] Total time:  02:24 min
2021-02-18T13:46:21.9606580Z [INFO] [INFO] Finished at: 2021-02-18T13:46:21Z
2021-02-18T13:46:21.9608560Z [INFO] [INFO] ------------------------------------------------------------------------
2021-02-18T13:46:21.9611884Z [INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22
```

am I missing anything?

that is why I eventually got rid of this profile in https://github.com/quarkiverse/quarkus-freemarker/commit/2a45705063e35147000bffee53ebe105215d0293

I fear that if we go back with your change, we are going to have the same issue during the release.
but we can definitely try. WDYT?

**Comment by gsmet** [comment]
Are you sure this is the `release:perform` step?

Because the `release:prepare` step should be executed for all the modules as it adjusts the version.
And then the `release:perform` step is executed ITs excluded.

I think it didn't work at first because you didn't have the `-DperformRelease=true` for `release:perform`. Now that you added it, it should work as expected.

I have the same setup for the OpenCV extension and it works well.

**Comment by gsmet** [comment]
See https://search.maven.org/search?q=quarkus-opencv , no ITs :).

**Comment by vsevel** [comment]
ok. so let's merge and release then

**Comment by vsevel** [comment]
```
2021-02-18T13:42:25.8930883Z [36;1mmvn -B release:prepare -Prelease -DreleaseVersion=0.2.0.CR1 -DdevelopmentVersion=0.2.0-SNAPSHOT -s maven-settings.xml[0m
2021-02-18T13:42:25.8932997Z [36;1mgit checkout master[0m
2021-02-18T13:42:25.8934279Z [36;1mgit rebase release[0m
2021-02-18T13:42:25.8936263Z [36;1mmvn -B release:perform -Darguments=-DperformRelease -DperformRelease -Prelease -s maven-settings.xml[0m
...
2021-02-18T13:43:14.0365690Z [INFO] Inspecting build with total of 7 modules...
2021-02-18T13:43:14.0373541Z [INFO] Installing Nexus Staging features:
2021-02-18T13:43:14.0384260Z [INFO]   ... total of 7 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
2021-02-18T13:43:14.0410894Z [INFO] ------------------------------------------------------------------------
2021-02-18T13:43:14.0415442Z [INFO] Reactor Build Order:
2021-02-18T13:43:14.0418495Z [INFO] 
2021-02-18T13:43:14.0438444Z [INFO] Quarkus - Freemarker - Parent                                      [pom]
2021-02-18T13:43:14.0447167Z [INFO] Quarkus - Freemarker - Runtime                                     [jar]
2021-02-18T13:43:14.0454382Z [INFO] Quarkus - Freemarker - Deployment                                  [jar]
2021-02-18T13:43:14.0459233Z [INFO] Quarkus - Freemarker - Integration tests                           [pom]
2021-02-18T13:43:14.0467609Z [INFO] Quarkus - Freemarker - Integration test - Configuration defaults   [jar]
2021-02-18T13:43:14.0475572Z [INFO] Quarkus - Freemarker - Integration test - Legacy configuration     [jar]
2021-02-18T13:43:14.0483540Z [INFO] Quarkus - Freemarker - Integration test - Template sets            [jar]
```

I do not know how to read those logs.
what is the build order associated with? release prepare or perform?
I am running a release on 0.2.3. we'll see. https://github.com/quarkiverse/quarkus-freemarker/pull/73

**Comment by vsevel** [comment]
see, again the same issue:
https://github.com/quarkiverse/quarkus-freemarker/actions/runs/582523030

```
2021-02-19T20:08:33.8705760Z [INFO] [INFO] -------------------------------------------------------
2021-02-19T20:08:33.8707642Z [INFO] [INFO]  T E S T S
2021-02-19T20:08:33.8709445Z [INFO] [INFO] -------------------------------------------------------
2021-02-19T20:08:34.8584528Z [INFO] [INFO] Running io.quarkiverse.it.freemarker.ConfigDefaultsTest
2021-02-19T20:08:35.7590504Z [INFO] Downloading from central: https://repo.maven.apache.org/maven2/io/quarkiverse/freemarker/quarkiverse-freemarker-integration-tests/0.2.3/quarkiverse-freemarker-integration-tests-0.2.3.pom
2021-02-19T20:08:36.2537665Z [INFO] [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 1.361 s <<< FAILURE! - in io.quarkiverse.it.freemarker.ConfigDefaultsTest
```

I don't know why config defaults tries to download `quarkiverse-freemarker-integration-tests-0.2.3.pom`
one difference (as with other extensions) is that `openCV` does not have multi IT modules.

**Comment by gsmet** [comment]
I’ll have a look. There must be something weird going on.

**Pull request merged**
