### PR TITLE
Various fixes and improvements

### PR DESCRIPTION
**Pull request by gsmet**
To be reviewed commit per commit.

Open to discussion obviously as some of the changes break compatibility but I think it's for the best.

/cc @ppalaga you might want to test this PR as you had the initialization issue that is definitely fixed by using the synthetic bean pattern.

### CODE REVIEW

**Review by ppalaga — APPROVED** [review]
Thanks @gsmet, looks good!

Backwards compatibility is not an issue for Camel Quarkus, because we released 1.7.0 without Freemarker native support.

**Comment by gsmet** [comment]
@vsevel friendly ping :). Have you seen this PR? Does it make any sense? :)

**Comment by vsevel** [comment]
@gsmet yes. sorry. I have been busy. I will go through it tomorrow.

**Comment by vsevel** [comment]
the breaking change is limited to the `directives` config property, right?
I agree it is consistent with quarkus (I did a quick review), and it is applied consistently.
out of curiosity, why is the synthetic bean pattern works here, where the simple recorder does not?

**Review by vsevel — APPROVED** [review]

**Comment by gsmet** [comment]
The recorder pattern sort of works but you can have race conditions (typically like this one: https://github.com/quarkiverse/quarkus-freemarker/pull/68 ).

With a synthetic bean, you use constructor injection so you are totally sure your config is properly injected and you won't have any race conditions.

Note that what you did is the pattern we had everywhere in Quarkus before synthetic beans and we were playing whack a mole with NPEs :).

**Comment by gsmet** [comment]
The two breaking changes are:
- the directives config
- the new deployment sub package (if your build items are consumed by others). I think the project is young enough for us to make this change now.

**Pull request merged**
