### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by vsevel**

### CODE REVIEW

**Comment by vsevel** [comment]
@ppalaga release done

**Comment by ppalaga** [comment]
Perfect, thanks!

**Comment by ppalaga** [comment]
0.2.0 still not available at https://repo1.maven.org/maven2/io/quarkiverse/freemarker/quarkus-freemarker/
Maybe you need to release the staging repo at https://oss.sonatype.org/ ?

**Comment by vsevel** [comment]
yes I saw this morning
I created https://github.com/quarkiverse/quarkus-freemarker/issues/54
the issue was introduced with introducing an `integration-tests`module
the release actually failed on the legacy tests, searching for `integration-tests:0.2.0` pom
I am not sure what is the proper way to fix it.

**Comment by vsevel** [comment]
@ppalaga at last we got a 0.2.0!
the only workaround I found was to deploy the test modules as well.
it is not pretty, and master has been messed up with my different trys, but at least we have a release, which buys us some time to make it better later.

**Pull request merged**
